name: Netcore

# Run this workflow ever time code is pushed to a branch
# other than `main` in your repository
on:
  pull_request:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal


    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply Auto changes
